### PR TITLE
Limit the number of ticks. See vega/vega-parser#59

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by jheer** [comment]
Thanks! This is a great start. I noted a couple things to consider:
- [AxisTicks.js#L35](https://github.com/vega/vega-encode/blob/master/src/AxisTicks.js#L35) automatically uses the length of an explicitly provided array as the tickCount. I think this should instead defer to the `tickCount` parameter if it is non-null. Note that the tickFormat takes the count as an input (and passes it to D3 scale's format method), and so formatting may in some cases be affected.
- In the case to `time` and `utc` scales, the `tickCount` parameter may be non-numeric, instead indicating a [time interval](https://github.com/vega/vega-encode/blob/master/src/ticks.js#L23). The new tick filtering should be sensitive to this. One possibility may be to only perform filtering when the count is indeed a number. The existing `count > 0` check should enforce this, but just want to make sure we fully consider the interval case as well.
- The [label overlap procedure](https://github.com/vega/vega-view-transforms/blob/master/src/Overlap.js#L79) includes some additional analysis when there are less than 3 ticks and the last tick has been filtered. In those cases some adjustment will be made to ensure the first and last tick (i.e., instead of a penultimate tick) are included. Perhaps we want to do something similar here?

**Comment by domoritz** [comment]
@jheer Thanks for the suggestions. I tried to address them in 8ae70b1.

**Comment by domoritz** [comment]
This change is needed for https://github.com/vega/vega-lite/issues/2942

**Comment by domoritz** [comment]
@jheer I have some time again and would like to get this in so we can make the VL 2.0 release.

**Pull request merged**
